name: Backend_Build

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]

permissions:
  contents: read

jobs:
  build:
    environment: Prod
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Creating .env
      working-directory: ${{ env.working-directory }}
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SWAGGER_PREFIX: ${{ secrets.SWAGGER_PREFIX }}
      run: |
        echo "DB_HOST=$DB_HOST" >> .env
        echo "DB_PORT=$DB_PORT" >> .env
        echo "POSTGRES_USER=$POSTGRES_USER" >> .env
        echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
        echo "SECRET_KEY=$SECRET_KEY" >> .env
        echo "SWAGGER_PREFIX=$SWAGGER_PREFIX" >> .env
      
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Check directory
      working-directory: ${{ env.working-directory }}
      run: cat Dockerfile

    - name: Build and release to DockerHub
      working-directory: ${{ env.working-directory }}
      env:
        NAME: ${{ secrets.DOCKERHUB_USERNAME }}
        REPO: 11m-backend
      run: |
        docker build -t $REPO .
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest

  deploy:
    needs: build
    environment: Prod
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            backend/start.sh
        
