name: Backend_Build

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    steps:
    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Build and release to DockerHub
      env:
        NAME: $${secrets.DOCKERHUB_USERNAME}}
        REPO: 11m-backend
      run: |
        docker build -t $REPO .
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest
