name: Backend_Build

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
