name: Backend_Build

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]

permissions:
  contents: read

jobs:
  build:
    environment: Prod
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Check directory
      working-directory: ${{ env.working-directory }}
      run: cat Dockerfile

    - name: Build and release to DockerHub
      working-directory: ${{ env.working-directory }}
      env:
        NAME: ${secrets.DOCKERHUB_USERNAME}}
        REPO: 11m-backend
      run: |
        docker build -t $REPO .
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest
